# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: science in bioinfor
brief-intro: I Am Nothing without you !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bioinforsky.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username: bioinforsky
email: lipmvip1@gmail.com
# twitter_username: gaohaoyang126
# facebook_username: gaohaoyang.water
# weibo_username: 3115521wh
# zhihu_username: gaohaoyang
# linkedIn_username: gaohaoyang
# dribbble_username:


description_footer: Want to Communicate with Me? 

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #bioinforsky
disqus_shortname: bioinforsky

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 1254ab36f678aa68dc32ff296b245600
google_analytics_id: UA-90384995-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
